name: 编译mt6833-安卓12内核
            支持ksu docker lxc

on:
  workflow_dispatch:

    inputs:
      KERNEL_BRANCH:
        description: 'KERNEL_BRANCH'
        required: true
        default: 'A124.19'
        type: choice
        options:
        - A124.19
      KERNEL_NAME:
        description: 'KERNEL_NAME'
        required: true
        default: 'kerne-l4.19'
        type: choice
        options:
        - kerne-l4.14
        - kerne-l4.19
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2



    - name: 构建编译内核环境
      run: |
        sudo apt-get update
        sudo -E apt-get -y -qq install git make bc bison ccache openssl dos2unix zip kmod cpio flex libelf-dev curl libssl-dev libtfm-dev wget device-tree-compiler ca-certificates python3 python2 binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace



    - name: 下载 Gcc编译器
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        
        mkdir gcc64
        wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc64/ -zxvf gcc-aarch64.tar.gz
    
        mkdir gcc32
        wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc32/ -zxvf gcc-arm.tar.gz
    
    - name: 下载Clang编译器
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir clang-aosp
        git clone -q --depth=1 https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6443078 -b 10.0 clang-aosp
    
    
    - name: 下载内核源码
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/Winkmoon/android_kernel_mtk6833.git -b ${{ github.event.inputs.KERNEL_BRANCH }} ${{ github.event.inputs.KERNEL_NAME }}
        cd ${{ github.event.inputs.KERNEL_NAME }}
        rm -rf KernelSU

    - name: 下载内核模块
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/Winkmoon/ShirokoNeko_OPPO_kernel_modules_mtk6833-4.19.git -b ${{ github.event.inputs.KERNEL_BRANCH }} vendor
        mkdir vnd
        cp -r vendor vnd/
              
    - name: 设置ccache缓存
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-mido-kernel
        max-size: 10G

 
    - name: 开始编译内核
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/${{ github.event.inputs.KERNEL_NAME }}
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc64/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc32/bin:$PATH
        export KBUILD_BUILD_HOST=ShirokoNeko酷安@欣然酱_official
        export KBUILD_BUILD_USER=ShirokoNeko-KSU-docker-lxc-v1debug
        make -s -j$(nproc --all) O=out ARCH=arm64 stock_defconfig
        make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- LD=ld.lld
                

        

    - name: 上传编译内核
      uses: actions/upload-artifact@v3
      with:
        name: mtk6833内核-Image
        path: kernel_workspace/${{ github.event.inputs.KERNEL_NAME }}/out/arch/arm64/boot/Image
